export enum SORT {
  DATE_CREATED_ASC = 'DATE_CREATED_ASC',
  DATE_CREATED_DESC = 'DATE_CREATED_DESC',
  NAME_ASC = 'NAME_ASC',
  NAME_DESC = 'NAME_DESC',
}

export enum USER {
  FOLLOWER_COUNT_DESC = 'FOLLOWER_COUNT_DESC',
  DATE_CREATED_DESC = 'DATE_CREATED_DESC',
  NICKNAME_ASC = 'NICKNAME_ASC',
  NICKNAME_DESC = 'NICKNAME_DESC',
}
