export enum SORT {
  DATE_CREATED_ASC = 'DATE_CREATED_ASC',
  DATE_CREATED_DESC = 'DATE_CREATED_DESC',
  NAME_ASC = 'NAME_ASC',
  NAME_DESC = 'NAME_DESC',
}

export enum USER {
  FOLLOWER_COUNT_DESC = 'FOLLOWER_COUNT_DESC',
  DATE_CREATED_DESC = 'DATE_CREATED_DESC',
  NICKNAME_ASC = 'NICKNAME_ASC',
  NICKNAME_DESC = 'NICKNAME_DESC',
}

export enum OPEN_TYPE {
  ALL_OPEN = 'ALL_OPEN',
  FOLLOWER_OPEN = 'FOLLOWER_OPEN',
  CLOSED = 'CLOSED',
}

export enum REPEAT_TYPE {
  DAILY = 'DAILY',
  WEEKLY = 'WEEKLY',
  MONTHLY = 'MONTHLY',
  YEARLY = 'YEARLY',
  ONCE = 'ONCE',
}

export enum DAY_NAME {
  월 = 'MONDAY',
  화 = 'TUESDAY',
  수 = 'WEDNESDAY',
  목 = 'THURSDAY',
  금 = 'FRIDAY',
  토 = 'SATURDAY',
  일 = 'SUNDAY',
}
